My implementation isn't thread safe due to the sd_err not being synced. The reason for this is that it uses sd_err to know whether the read_secto call resulted in an error or succeeded. It's possible that a thread for which the call actually succeeded gets an error and fails to reada, or worse yet, a thread which fails to read thinks it gets a successful response, and as a result reads something that it shouldn't.
